[package]
name = "mpw_client"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.57", features = ["derive"] }
mpw_daemon = { path = "../mpw_daemon" }
serde_json = "1.0.149"
shellexpand = "3.1.1"
secure-string = "0.3.0"
